Work around bugprone-use-after-move clang-tidy warning after clang update
After clang update, clang-tidy bugprone-use-after-move starts to check
constructor initialization list. It gives below false-positive warning:

art/libartbase/base/scoped_arena_allocator.cc:122:20: error: 'other' used after it
  was moved [bugprone-use-after-move,-warnings-as-errors]
arena_stack_(other.arena_stack_),
^
art/libartbase/base/scoped_arena_allocator.cc:119:7: note: move occurred here
: DebugStackReference(std::move(other)),
^

To work around this, use static_case to right reference instead.

Bug: 286421006
Test: build with clang-r498229
Change-Id: Icac433d9bf1600546b5f7cf7bc6c520d61d020c2