Update patch set 8
Patch Set 8:

> FAIL: Some checks failed. See below.
 > 
 > 
The failures are due to b/30419309 and should be fixed by the upcoming Clang update:
fatal error: error in backend: ran out of registers during register allocation

Patch-set: 8