Update patch set 7
Patch Set 7:

> === Finished presubmit run: L52600000097510599 ===

[…]

 > FAIL: Some checks failed. See below.

[…]

 > === git_master/gce_x86_phone-userdebug_fastbuild3c_linux ===
 > 
 > FAIL: Failed to build git_master/test_suites_x86_64_fastbuild3d_linux/4304312
 > (ToT). See https://android-build.googleplex.com/builds/pending/P4713034/test_suites_x86_64_fastbuild3d_linux/latest

Petre-Ionut, you probably cannot access the logs, so I copied the build error below:

  make -j80 cts showcommands dist DIST_DIR=/buildbot/dist_dirs/git_master-fastbuild3d_linux-test_suites_x86_64/P4713034/0 TARGET_PRODUCT=aosp_x86_64 WITH_DEXPREOPT=false BUILD_GOOGLE_VTS=true ats dts gts pts vts google-tradefed-all general-tests
  FAILED: out/soong/.intermediates/hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest/android_x86_x86_64_core/obj/hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.o 
  PWD=/proc/self/cwd prebuilts/misc/linux-x86/ccache/ccache prebuilts/clang/host/linux-x86/clang-4053586/bin/clang++ -c -Ihardware/interfaces/neuralnetworks/1.0/vts/functional  -fno-exceptions -Wno-multichar -O2 -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -ffunction-sections -fno-short-enums -fstrict-aliasing -funwind-tables -fstack-protector-strong -no-canonical-prefixes -O2 -g -fno-strict-aliasing -msse3 -mstackrealign -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -fdebug-prefix-map=$PWD/= -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -nostdlibinc -m32 -march=prescott -DUSE_SSSE3 -mssse3 -msse4 -msse4.1 -msse4.2 -Iexternal/googletest/googletest/include -Itest/vts/runners/target/vts_hal_hidl_target -Isystem/libhidl/base/include -Isystem/core/libcutils/include -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/liblog/include -Isystem/core/libsystem/include -Isystem/libhidl/transport/include -Isystem/core/base/include -Iout/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.1/android.hidl.manager@1.1_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen -Isystem/libhwbinder/include -Iout/soong/.intermediates/hardware/interfaces/neuralnetworks/1.0/android.hardware.neuralnetworks@1.0_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/allocator/1.0/android.hidl.allocator@1.0_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/memory/1.0/android.hidl.memory@1.0_genc++_headers/gen -Isystem/libhidl/libhidlmemory/include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Ilibnativehelper/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include -isystem bionic/libc/arch-x86/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-x86 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -Ilibnativehelper/include_deprecated -Wall -Werror -O0 -g -target i686-linux-android -Bprebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/x86_64-linux-android/bin -DANDROID_STRICT -fPIE -DGTEST_HAS_STD_STRING -DGTEST_OS_LINUX_ANDROID -D_USING_LIBCXX -std=gnu++14 -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -MD -MF out/soong/.intermediates/hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest/android_x86_x86_64_core/obj/hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.o.d -o out/soong/.intermediates/hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest/android_x86_x86_64_core/obj/hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.o hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.cpp
  hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.cpp:43:25: error: 'IDevice' does not refer to a value
      registerTestService<IDevice>();
                          ^
  out/soong/.intermediates/hardware/interfaces/neuralnetworks/1.0/android.hardware.neuralnetworks@1.0_genc++_headers/gen/android/hardware/neuralnetworks/1.0/IDevice.h:21:8: note: declared here
  struct IDevice : public ::android::hidl::base::V1_0::IBase {
         ^
  hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.cpp:43:34: error: expected expression
      registerTestService<IDevice>();
                                   ^
  hardware/interfaces/neuralnetworks/1.0/vts/functional/VtsHalNeuralnetworksV1_0TargetTest.cpp:48:14: error: no matching function for call to 'getService'
      device = ::testing::VtsHalHidlTargetTestBase::getService<IDevice>(
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  test/vts/runners/target/vts_hal_hidl_target/VtsHalHidlTargetTestBase.h:90:16: note: candidate function not viable: no known conversion from 'android::hardware::neuralnetworks::V1_0::vts::functional::NeuralnetworksHidlEnvironment *' to 'const std::__1::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') for 1st argument
    static sp<T> getService(const string& serviceName = "default") {
                 ^
  test/vts/runners/target/vts_hal_hidl_target/VtsHalHidlTargetTestBase.h:98:16: note: candidate function not viable: no known conversion from 'android::hardware::neuralnetworks::V1_0::vts::functional::NeuralnetworksHidlEnvironment *' to 'const char *' for 1st argument
    static sp<T> getService(const char serviceName[]) {
                 ^
  test/vts/runners/target/vts_hal_hidl_target/VtsHalHidlTargetTestBase.h:106:16: note: candidate function not viable: no known conversion from 'android::hardware::neuralnetworks::V1_0::vts::functional::NeuralnetworksHidlEnvironment *' to 'const ::android::hardware::hidl_string' for 1st argument
    static sp<T> getService(const ::android::hardware::hidl_string& serviceName) {
                 ^
  3 errors generated.

Patch-set: 7
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>