Update patch set 7
Patch Set 7:

> Xueliang, error is:
 > 
 > Machine: prod16-rrwl
 > make -j80 PRODUCT-aosp_x86-eng showcommands dist DIST_DIR=/buildbot/dist_dirs/aosp-master-linux-aosp_x86-eng/P4512901/0
 > checkbuild
 > FAILED: out/soong/.intermediates/art/compiler/libart-compiler/android_x86_static_core/obj/art/compiler/optimizing/scheduler.o
 > PWD=/proc/self/cwd prebuilts/misc/linux-x86/ccache/ccache
 > prebuilts/clang/host/linux-x86/clang-4053586/bin/clang++ -c
 > -Iart/compiler -Ibionic/libc/private -Iexternal/icu/icu4c/source/common
 > -Iexternal/lz4/lib -Iexternal/valgrind/include -Iexternal/valgrind
 > -Iexternal/vixl/src -Iexternal/zlib -Ilibnativehelper/platform_include
 > -Iart/disassembler -Iart/compiler  -fno-exceptions -Wno-multichar
 > -O2 -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2
 > -Wstrict-aliasing=2 -ffunction-sections -fno-short-enums
 > -fstrict-aliasing -funwind-tables -fstack-protector-strong
 > -no-canonical-prefixes -O2 -g -fno-strict-aliasing -msse3
 > -mstackrealign -DANDROID -fmessage-length=0 -W -Wall -Wno-unused
 > -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd=
 > -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion
 > -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument
 > -fcolor-diagnostics -Wno-expansion-to-defined -fdebug-prefix-map=$PWD/=
 > -Werror=return-type -Werror=non-virtual-dtor -Werror=address
 > -Werror=sequence-point -Werror=date-time -nostdlibinc -m32
 > -march=prescott -Iexternal/boringssl/src/include -Iexternal/libcxx/include
 > -Iexternal/libcxxabi/include -Isystem/core/base/include
 > -Iexternal/lz4/lib -Iexternal/lzma/C -Iart/runtime
 > -Iout/soong/.intermediates/art/tools/cpp-define-generator/cpp-define-generator-asm-support/gen
 > -Iart/dexlayout -Isystem/core/libcutils/include -Iout/soong/.intermediates/art/compiler/art_compiler_operator_srcs/gen
 > -Isystem/core/include -Isystem/media/audio/include
 > -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include
 > -Ihardware/ril/include -Ilibnativehelper/include -Iframeworks/native/include
 > -Iframeworks/native/opengl/include -Iframeworks/av/include -isystem
 > bionic/libc/arch-x86/include -isystem bionic/libc/include -isystem
 > bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-x86
 > -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi
 > -Ilibnativehelper/include/nativehelper -fno-rtti -ggdb3 -Wall
 > -Werror -Wextra -Wstrict-aliasing -fstrict-aliasing
 > -Wunreachable-code -Wredundant-decls -Wshadow -Wunused
 > -fvisibility=protected -Wthread-safety -Wthread-safety-negative
 > -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast
 > -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break
 > -Wunreachable-code-return -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
 > -O3 -DART_DEFAULT_GC_TYPE_IS_CMS -DART_ENABLE_VDEX -DIMT_SIZE=43
 > -DART_USE_READ_BARRIER=1 -DART_READ_BARRIER_TYPE_IS_BAKER=1
 > -DART_STACK_OVERFLOW_GAP_arm=8192 -DART_STACK_OVERFLOW_GAP_arm64=8192
 > -DART_STACK_OVERFLOW_GAP_mips=16384 -DART_STACK_OVERFLOW_GAP_mips64=16384
 > -DART_STACK_OVERFLOW_GAP_x86=8192 -DART_STACK_OVERFLOW_GAP_x86_64=8192
 > -DART_TARGET -Wmissing-noreturn -DART_ENABLE_CODEGEN_x86
 > -Wframe-larger-than=1736 -DART_FRAME_SIZE_LIMIT=1736
 > -DART_BASE_ADDRESS=0x70000000 -DART_TARGET_ANDROID
 > -DART_BASE_ADDRESS_MIN_DELTA=-0x1000000 -DART_BASE_ADDRESS_MAX_DELTA=0x1000000
 > -target i686-linux-android -Bprebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/x86_64-linux-android/bin
 > -DANDROID_STRICT -fPIC -D_USING_LIBCXX -std=gnu++14 -Wsign-promo
 > -Wno-inconsistent-missing-override -Wno-null-dereference
 > -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative
 > -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast
 > -Werror=address-of-temporary -Werror=return-type -MD -MF
 > out/soong/.intermediates/art/compiler/libart-compiler/android_x86_static_core/obj/art/compiler/optimizing/scheduler.o.d
 > -o out/soong/.intermediates/art/compiler/libart-compiler/android_x86_static_core/obj/art/compiler/optimizing/scheduler.o
 > art/compiler/optimizing/scheduler.cc
 > In file included from art/compiler/optimizing/scheduler.cc:20:
 > art/compiler/optimizing/scheduler.h:501:24: error: private field
 > 'codegen_' is not used [-Werror,-Wunused-private-field]
 > CodeGenerator* const codegen_;
 > ^
 > 1 error generated.
Hi Nicolas, sorry I forgot to test Intel backends as well. The small change in PS7 should fix this build failure in x86 backend.

Patch-set: 7
Reviewer: Gerrit User 1096678 <1096678@85c56323-6fa9-3386-8a01-6480fb634889>