Update patch set 1
Patch Set 1: Presubmit-Ready+1

I'm getting the following when I try to run tests, is there something special I need to do?

$ ./test/run-test --host --dev 115-native-bridge
/android/aosp/art/test/115-native-bridge: building...
Error: Missing out/host/linux-x86/framework/desugar.jar; did you do a build?

Patch-set: 1
Reviewer: Gerrit User 1041833 <1041833@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1003224 <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1079148 <1079148@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1