Revert^2: "Make sigchain actually own the signal chain.""
Hopefully fix the following darwin build breakage and unrevert:

  MacOSX10.10.sdk/usr/include/ucontext.h:43:2:
    error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined

This reverts commit 33dca562d5ed9f52f63ced2334c066333ca073e9.

Bug: http://b/36205469
Bug: http://b/36262089
Original-Change-Id: I416b13de800d3e23424cf20688ccfd7e4e48a111
Change-Id: I1267be72c32ed73d1079a572d0b8907556526dde