Error fix from enabling Clang thread-safety checks.
Parent bug: b/353324127. Enabling `thread-safety-reference-return`
to allow developers to utilize Clang thread safety guardrails
(GUARDED_BY, REQUIRES, EXCLUDES).

Errors:
art/runtime/jit/debugger_interface.cc:222:47: error: returning variable
'__dex_debug_descriptor' by reference requires holding mutex 'g_dex_debug_lock'
exclusively [-Werror,-Wthread-safety-reference-return]
art/runtime/jit/debugger_interface.cc:231:47: error: returning variable
'__jit_debug_descriptor' by reference requires holding mutex 'g_jit_debug_lock'
exclusively [-Werror,-Wthread-safety-reference-return]

Fix: return by value, hold mutex from parent, or remove GUARDED_BY
attribute.

This fix removes the GUARDED_BY attribute in order to avoid changing
functionality. If this is not desired, please respond with concerns
or preferred fix.

Change-Id: I930b8fd4efdd09af04360446d72bd393dc593f65
Bug: 353323313
Test: make