Update patch set 5
Patch Set 5:

> FAIL: All checks failed. See below.
 > 
 > FAIL: Failed to build aosp-master/aosp_arm64-eng. See
 > https://android-build.googleplex.com/builds/pending/P2814785/aosp_arm64-eng/latest.
 > 
 > Found a submit queue bug? Have a question? http://go/treehugger-submitqueue-bug

  art/compiler/optimizing/inliner.cc:659:63: error: no member named 'kVTable' in 'art::HClassTableGet'
        invoke_instruction->IsInvokeVirtual() ? HClassTableGet::kVTable : HClassTableGet::kIMTable,
                                                ~~~~~~~~~~~~~~~~^
  art/compiler/optimizing/inliner.cc:659:89: error: no member named 'kIMTable' in 'art::HClassTableGet'
        invoke_instruction->IsInvokeVirtual() ? HClassTableGet::kVTable : HClassTableGet::kIMTable,
                                                                          ~~~~~~~~~~~~~~~~^
  2 errors generated.

That's probably because `HClassTableGet::TableKind` is now an `enum class`; somes uses of enum values must lack the `TableKind` explicit scope qualifier.

Patch-set: 5