Update patch set 2
Patch Set 2:

Here is one example (derived from test/014-math3/src/Main.java) to show the issue.
Ex:
public class Main {
    public static void math_014() {
        int expectedThrows = 2;
        int i;
        long j;
        float f = 0.0f;
        double d = 0.0;

        i = 10 / 0;
    }
    public static void main(String args[]) {
        math_014();
    }
}

Without this patch, we will get seg fault.
Ex:
Program received signal SIGSEGV, Segmentation fault.
art::mirror::ObjectReference<false, art::mirror::Class>::UnCompress() const ()
    at art/runtime/mirror/object_reference.h:66
66	    uintptr_t as_bits = kPoisonReferences ? -reference_ : reference_;
(gdb) bt
#0  art::mirror::ObjectReference<false, art::mirror::Class>::UnCompress() const ()
    at art/runtime/mirror/object_reference.h:66
#1  0x00007ffff67abad5 in art::mirror::ObjectReference<false, art::mirror::Class>::AsMirrorPtr() const ()
    at art/runtime/mirror/object_reference.h:37
#2  0x00007ffff67abaa2 in art::mirror::Class* art::ReadBarrier::Barrier<art::mirror::Class, (art::ReadBarrierOption)0>(art::mirror::Object*, art::MemberOffset, art::mirror::HeapReference<art::mirror::Class>*) ()
    at art/runtime/read_barrier-inl.h:42
#3  0x00007ffff67aba1a in art::mirror::Class* art::mirror::Object::GetFieldObject<art::mirror::Class, (art::VerifyObjectFlags)0, (art::ReadBarrierOption)0, false>(art::MemberOffset) ()
    at art/runtime/mirror/object-inl.h:549
#4  0x00007ffff67aaea7 in art::mirror::Class* art::mirror::Object::GetClass<(art::VerifyObjectFlags)0, (art::ReadBarrierOption)0>() () at art/runtime/mirror/object-inl.h:39
#5  0x00007ffff6a02c4f in art::StackVisitor::SanityCheckFrame() const () at art/runtime/stack.cc:273
#6  0x00007ffff6a020e0 in art::StackVisitor::WalkStack(bool) () at art/runtime/stack.cc:311
#7  0x00007ffff6a0bf96 in art::Thread::GetCurrentLocationForThrow() () at art/runtime/thread.cc:1931
#8  0x00007ffff680fb5c in art::ThrowException(art::ThrowLocation const*, char const*, art::mirror::Class*, char const*, __va_list_tag (*) [1]) () at art/runtime/common_throws.cc:62
  
2: void Main.math_014() (dex_method_idx=2)
    DEX CODE:
      0x0000: const/4 v2, #+2
      0x0001: const/4 v3, #+0
      0x0002: const-wide/16 v0, #+0
      0x0004: const/16 v5, #+10
      0x0006: div-int/lit8 v4, v5, #+0
      0x0008: return-void
    OAT DATA:
      frame_size_in_bytes: 48
      core_spill_mask: 0x00010000 (r16)
      fp_spill_mask: 0x00000000 
      vmap_table: 0x7fbdf60e3404 (offset=0x00000404)
      v65535/r16
      mapping_table: 0x7fbdf60e33f9 (offset=0x000003f9)
      gc_map: 0x7fbdf60e33e8 (offset=0x000003e8)
    CODE: 0x7fbdf60e40ec (offset=0x000010ec size=64)...
      0x7fbdf60e40ec:               4883EC28            sub     rsp, 40
      0x7fbdf60e40f0:                 893C24            mov     [esp], edi
      0x7fbdf60e40f3:             BA02000000            mov     edx, 2
      0x7fbdf60e40f8:               89542414            mov     [esp + 20], edx
      0x7fbdf60e40fc:                   33F6            xor     esi, esi
      0x7fbdf60e40fe:               89742418            mov     [esp + 24], esi
      0x7fbdf60e4102:       C744240C00000000            mov     [esp + 12], 0
      0x7fbdf60e410a:       C744241000000000            mov     [esp + 16], 0
      0x7fbdf60e4112:             BF0A000000            mov     edi, 10
      0x7fbdf60e4117:               897C2420            mov     [esp + 32], edi
      0x7fbdf60e411b:                   EB05            jmp     +5 (0x7fbdf60e4122)
      0x7fbdf60e411d:               4883C428            add     rsp, 40
      0x7fbdf60e4121:                     C3            ret     
      0x7fbdf60e4122:       65FF142530050000            call    gs:[1328]  ; pThrowDivZero
      suspend point dex PC: 0x0006
      0x7fbdf60e412a:                   0000            add     [eax], al


With my patch, divide by zero is thrown.
Ex:
java.lang.ArithmeticException: divide by zero
	at Main.math_014(Main.java:28)
	at Main.main(Main.java:63)
    CODE: 0x7f4d5aece0ec (offset=0x000010ec size=68)...
      0x7f4d5aece0ec:               4883EC28            sub     rsp, 40
      0x7f4d5aece0f0:                 893C24            mov     [esp], edi <-- TOO BAD, BECAUSE WE ONLY FLUSH 4 BYTES.
      0x7f4d5aece0f3:               48893C24            mov     [rsp], rdi <-- A NEW INSTRUCTION
      0x7f4d5aece0f7:             BA02000000            mov     edx, 2
      0x7f4d5aece0fc:               89542414            mov     [esp + 20], edx
      0x7f4d5aece100:                   33F6            xor     esi, esi
      0x7f4d5aece102:               89742418            mov     [esp + 24], esi
      0x7f4d5aece106:       C744240C00000000            mov     [esp + 12], 0
      0x7f4d5aece10e:       C744241000000000            mov     [esp + 16], 0
      0x7f4d5aece116:             BF0A000000            mov     edi, 10
      0x7f4d5aece11b:               897C2420            mov     [esp + 32], edi
      0x7f4d5aece11f:                   EB05            jmp     +5 (0x7f4d5aece126)
      0x7f4d5aece121:               4883C428            add     rsp, 40
      0x7f4d5aece125:                     C3            ret     
      0x7f4d5aece126:       65FF142530050000            call    gs:[1328]  ; pThrowDivZero
      suspend point dex PC: 0x0006
      0x7f4d5aece12e:                   0000            add     [eax], al


The patch adds one instruction as "mov [rsp], rdi" after "mov [esp], edi", compared to the first version.  This instruction helps, because it clears out the upper 4 bytes of 8 bytes from offset 0 against the stack base. Also, please note that we need to have enough frame space to accommodate 8 bytes of Method*, as this patch addresses.  Thanks!

Patch-set: 2
Reviewer: Gerrit User 1010712 <1010712@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0