Update patch set 1
Patch Set 1:

> FAIL: All checks failed. See below.
 > 
 > FAIL: Failed to build aosp-master/aosp_arm64-eng. See
 > https://android-build.googleplex.com/builds/pending/P2806875/aosp_arm64-eng/latest.
 > 
 > Found a submit queue bug? Have a question? http://go/treehugger-submitqueue-bug

  art/dex2oat/dex2oat.cc: In function 'int art::dex2oat(int, char**)':
  art/dex2oat/dex2oat.cc:2557:38: error: 'make_unique' is not a member of 'std'
     std::unique_ptr<Dex2Oat> dex2oat = std::make_unique<Dex2Oat>(&timings);
                                        ^
  art/dex2oat/dex2oat.cc:2557:62: error: expected primary-expression before '>' token
     std::unique_ptr<Dex2Oat> dex2oat = std::make_unique<Dex2Oat>(&timings);

std::make_unique requires C++14; I'll use art::MakeUnique instead.

Patch-set: 1
Label: Verified=0