Update patch set 6
Patch Set 6:

Fails for me to compile as ARM64 hasn't been converted to member calls:


art/runtime/arch/arm64/thread_arm64.cc: In member function 'void art::Thread::InitCpu()':
art/runtime/arch/arm64/thread_arm64.cc:25:115: error: 'class art::Thread' has no member named 'state_and_flags_'
   CHECK_EQ(THREAD_FLAGS_OFFSET, OFFSETOF_MEMBER(Thread, state_and_flags_));
                                                                                                                   ^
art/runtime/arch/arm64/thread_arm64.cc:26:115: error: 'class art::Thread' has no member named 'card_table_'
   CHECK_EQ(THREAD_CARD_TABLE_OFFSET, OFFSETOF_MEMBER(Thread, card_table_));
                                                                                                                   ^
art/runtime/arch/arm64/thread_arm64.cc:27:116: error: 'class art::Thread' has no member named 'exception_'
   CHECK_EQ(THREAD_EXCEPTION_OFFSET, OFFSETOF_MEMBER(Thread, exception_));
                                                                                                                    ^
art/runtime/arch/arm64/thread_arm64.cc:28:117: error: 'class art::Thread' has no member named 'thin_lock_thread_id_'
   CHECK_EQ(THREAD_ID_OFFSET, OFFSETOF_MEMBER(Thread, thin_lock_thread_id_));

Patch-set: 6
Label: Verified=0