Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Presubmit failure:
> 
>   > [100% 154/154] out/multiproduct/sdk_phone_x86_vendor/soong/.bootstrap/bin/soong_build out/multiproduct/sdk_phone_x86_vendor/soong/build.ninja
>   > FAILED: out/multiproduct/sdk_phone_x86_vendor/soong/build.ninja
>   > out/multiproduct/sdk_phone_x86_vendor/soong/.bootstrap/bin/soong_build -t -l out/multiproduct/sdk_phone_x86_vendor/.module_paths/Android.bp.list --empty-ninja-file -b out/multiproduct/sdk_phone_x86_vendor/soong -n out/multiproduct/sdk_phone_x86_vendor -d out/multiproduct/sdk_phone_x86_vendor/soong/build.ninja.d -globFile out/multiproduct/sdk_phone_x86_vendor/soong/.bootstrap/build-globs.ninja -o out/multiproduct/sdk_phone_x86_vendor/soong/build.ninja Android.bp
>   > error: art/build/apex/Android.bp:517:1: "art-check-auto-flattened-apex-gen" depends on undefined module "{.flattened}"
>   > ninja: build stopped: subcommand failed.
>   > 15:00:41 soong bootstrap failed with: exit status 1
> 
> Looking into it.

I guess this build target does not define `PRODUCT_ART_APEX`…

Patch-set: 1
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>