Update patch set 8
Patch Set 8:

error: art/runtime/Android.bp:245:18: unrecognized property "use_clang_lld"

I guess this is still running against code that doesn't have your CLs merged yet.

Patch-set: 8
Reviewer: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>