Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  art/compiler/dex/quick/x86/int_x86.cc:867:22: error: use of undeclared identifier 'AllocFreeTemp'; did you mean 'AllocTemp'?
    RegStorage tmp = AllocFreeTemp();
                     ^~~~~~~~~~~~~
                     AllocTemp
art/compiler/dex/quick/mir_to_lir.h:750:24: note: 'AllocTemp' declared here
    virtual RegStorage AllocTemp(bool required = true);
                       ^
1 error generated.
make: *** [out/host/linux-x86/obj32/SHARED_LIBRARIES/libart-compiler_intermediates/dex/quick/x86/int_x86.o] Error 1



If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Reviewer: Gerrit User 1006433 <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1