Fix thread-safety-analysis warning on Clang r484197
art/runtime/mirror/dex_cache.h:177:36: error: calling function 'ObjPtr<art::mirror::MethodType, void>' requires holding mutex 'mutator_lock_' [-Werror,-Wthread-safety-analysis]
    SetPair(index, DexCachePair<T>(value, index));
                                   ^
art/runtime/mirror/dex_cache.h:488:3: note: in instantiation of member function 'art::mirror::DexCachePairArray<art::mirror::MethodType, 1024>::Set' requested here
  DEFINE_DUAL_CACHE(resolved_method_types_,
  ^
art/runtime/mirror/dex_cache.h:456:18: note: expanded from macro 'DEFINE_DUAL_CACHE'
          pairs->Set(index, resolved); \
                 ^

This is due to improved Thread safety analysis in Clang:
https://github.com/llvm/llvm-project/commit/54bfd04846156dbd5e0a6b88f539c3d4569a455f

Test: build
Bug: 265153643
Change-Id: I50b34c5f0c43fcf7f909d145f86c46862966b46d