Update patch set 1
Patch Set 1:

adb install would cause this java exception for mips:

Failed to install cm3.apk: 
Exception occurred while dumping:
java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
	at java.lang.Integer.stringSize(Integer.java:501)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:657)
	at java.lang.StringBuilder.append(StringBuilder.java:209)
	at java.lang.ArrayIndexOutOfBoundsException.<init>(ArrayIndexOutOfBoundsException.java:83)
	at java.util.Arrays.checkOffsetAndCount(Arrays.java:4857)
	at android.os.FileBridge$FileBridgeOutputStream.write(FileBridge.java:179)
	at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(PackageManagerShellCommand.java:1179)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:149)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:94)
	at android.os.ShellCommand.exec(ShellCommand.java:94)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18161)
	at android.os.Binder.shellCommand(Binder.java:468)
	at android.os.Binder.onTransact(Binder.java:367)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2387)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3143)
	at android.os.Binder.execTransact(Binder.java:565)

I will change the title to be better describe the problem.

Patch-set: 1
Label: Verified=0