Update patch set 1
Patch Set 1:

> Which build did this break? I didn't see the problem locally and
 > didn't get mail from the build server.

It broke build 2171512 (aosp_flounder-userdebug_clang (linux) build in git_mirror-aosp-master-with-vendor):

  art/dex2oat/dex2oat.cc:545:8: error: stack frame size of 3096 bytes in function 'art::Dex2Oat::ParseArgs' [-Werror,-Wframe-larger-than=]
    void ParseArgs(int argc, char** argv) {
       ^
  1 error generated.
  make: *** [out/host/linux-x86/obj/EXECUTABLES/dex2oat_intermediates/dex2oat.o] Error 1

Patch-set: 1
Label: Verified=0