Revert "Revert "Revert "Revert "Make sure that const-class linkage is preserved.""""
Avoid class loading triggered by verification in the
626-const-class-linking test. Expect spurious wakeups.

Add extra debugging output for a very strange failure
    image_writer.cc:1144] Check failed:
    !IsBootClassLoaderClass(as_klass)
    java.lang.Class<java.lang.NoSuchMethodError>
That class is supposed to be in the boot image (core.art for
tests), so the failing check should not be reached at all.

Test: m test-art-host
Test: m ART_TEST_OPTIMIZING=true \
        ART_TEST_JIT=true \
        ART_TEST_INTERPRETER=true \
        ART_TEST_INTERPRETER_ACCESS_CHECKS=true \
        test-art-target-run-test-626-const-class-linking
Bug: 30627598

This reverts commit 09ded9201fbeec605b12741ae255663c14bda225.

Change-Id: I65a68cb53f0707b8abb3555ac3dc44c82907aef5