test: Enable 008-exceptions with --jvm
If a <clinit> fails because of a user-defined exception being thrown:
* On JVM the NoClassDefFoundError has an empty cause.
* On ART we stick the exception into the NCDFE.getCause().

Bug: 73888836
Test: art/test/testrunner/testrunner.py --jvm --host -t 008-exceptions
Change-Id: Ia6f4b9c91ad65bc3d53f496aaa2f6577c02f62a2