Declare OatWriter::BssMappingInfo sooner
The forward declaration of BssMappingInfo breaks this std::vector
field:

    std::vector<BssMappingInfo> bcp_bss_info_;

After upgrading libc++ and switching to C++20, there are build errors
complaining that BssMappingInfo is an incomplete type:

    error: arithmetic on a pointer to an incomplete type 'art::linker::OatWriter::BssMappingInfo'
    error: invalid application of 'sizeof' to an incomplete type 'art::linker::OatWriter::BssMappingInfo'

Some vector constructors become constexpr, which may be the cause.

Bug: 311052584
Test: atest art_standalone_dex2oat_tests
Change-Id: I808cf58a190598d4440294079f8d9e2997e4c8c2