Update patch set 1
Patch Set 1:

Actually that breaks with:
art/tools/cpp-define-generator/main.cc:101:5: error: stack frame size of 11608 bytes in function 'main' [-Werror,-Wframe-larger-than=]

I'll revert the original change. Igor, I'll let you fix it.

Patch-set: 1
Reviewer: Gerrit User 1038443 <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0