Update patch set 3
Patch Set 3:

> Merge conflicts. Hard to tell which CL in the topic.

Well, not so hard after all:

Git fetch succeeded: git fetch https://android-review.googlesource.com/a/device/google/crosshatch c118333fe9aeaf02aff71138fa79081f41de32e4
Executing: ['/bin/bash', '-c', 'git cherry-pick -Xpatience --keep-redundant-commits FETCH_HEAD'] from /buildbot/src/googleplex-android/master/device/google/crosshatch
error: could not apply c118333... Fix Pixel 3 cpu variant to kryo 385.

Roland has a modified CL for master that needs to be merged, then we need to add Merged-In:.

Patch-set: 3
Reviewer: Gerrit User 1018108 <1018108@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Autosubmit=0
Label: Presubmit-Ready=0