Update patch set 1
Patch Set 1:

errors while building without this:
art/runtime/base/logging.cc:258: error: undefined reference to '__android_log_print'
art/runtime/base/logging.cc:260: error: undefined reference to '__android_log_print'
art/runtime/base/logging.cc:258: error: undefined reference to '__android_log_print'
art/runtime/base/logging.cc:260: error: undefined reference to '__android_log_print'
art/runtime/base/logging.cc:288: error: undefined reference to '__android_log_write'
art/runtime/base/logging.cc:291: error: undefined reference to '__android_log_write'
art/runtime/monitor_android.cc:106: error: undefined reference to '__android_log_btwrite'
system/core/base/logging.cpp:243: error: undefined reference to '__android_log_buf_print'
system/core/base/logging.cpp:246: error: undefined reference to '__android_log_buf_print'
system/core/base/logging.cpp:243: error: undefined reference to '__android_log_buf_print'
system/core/base/logging.cpp:246: error: undefined reference to '__android_log_buf_print'

looks like it wouldn't because static libbase still references liblog

Patch-set: 1