Increase host frame size limit for SANITIZE_HOST
When SANITIZE_HOST=address, art/test/137-cfi/cfi.cc fails with:
error: stack frame size of 1944 bytes in function 'Java_Main_unwindInProcess'
Increase the frame size when SANITIZE_HOST is set, the same way it is
increased for device builds.

Test: m -j libarttest SANITIZE_HOST=address
Change-Id: I08d8492e6629159b0e0306cb9499debbe6bb865c