Update patch set 2
Patch Set 2:

It seems the Python 3 version running on our build machines does not know about f-strings (which where introduced in Python 3.6)…

  FAILED: out/soong/.intermediates/art/build/apex/art-check-debug-apex-gen/gen/art-check-debug-apex-gen.dummy
  out/soong/host/linux-x86/bin/sbox --sandbox-path out/soong/.temp --output-root out/soong/.intermediates/art/build/apex/art-check-debug-apex-gen/gen -c 'out/soong/host/linux-x86/bin/art-apex-tester --debugfs out/soong/host/linux-x86/bin/debugfs --tmpdir __SBOX_OUT_DIR__ --debug out/soong/.intermediates/art/build/apex/com.android.runtime.debug/android_common_com.android.runtime.debug/com.android.runtime.debug.apex && touch __SBOX_OUT_FILES__' __SBOX_OUT_DIR__/art-check-debug-apex-gen.dummy
  File "/mnt/disks/build-disk/src/android/master/out/soong/.temp/Soong.python_rmtSOg/art_apex_test.py", line 665
  print(f'[ n/a ] {val_path}')
  ^
  SyntaxError: invalid syntax

I'll revert to using %-formatting.

Patch-set: 2
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0