Update patch set 9
Patch Set 9:

> Patch Set 9:
> 
> > Patch Set 9: Code-Review-1
> > 
> > (1 comment)
> > 
> > We are being blocked by b/115717630 since the introduction of precise dependency tracking in APEXes added by https://android-review.googlesource.com/c/platform/build/soong/+/784216, as some of the included (target) binaries are built with `compile_multilib: "prefer32"` (dex2oat, dexoptanalyzer, profman). I've temporarily disabled this in PS9 to be able to build the ART APEX.
> 
> How about setting compile_multilib: "prefer32" to the apex module itself?

Sorry, I should have mentioned that I did try this last week (before coming up with the workaround to disable `compile_multilib: "prefer32"` in PS9), but it did not work, even with a smaller APEX module containing just `dex2oat`:

  apex {
      name: "com.android.art",
      manifest: "manifest.json",
      file_contexts: "file_contexts",
      binaries: ["dex2oat"],
      key: "apex.test.key",
  
      target: {
          android: {
              // Prefer the 32-bit versions of these binaries.
              compile_multilib: "prefer32",
          },
      },
  }

The error message is (for lunch target `aosp_taimen-userdebug`):

  $ make -j40 com.android.art
  ============================================
  PLATFORM_VERSION_CODENAME=Q
  PLATFORM_VERSION=Q
  TARGET_PRODUCT=aosp_taimen
  TARGET_BUILD_VARIANT=userdebug
  TARGET_BUILD_TYPE=release
  TARGET_ARCH=arm64
  TARGET_ARCH_VARIANT=armv8-a
  TARGET_CPU_VARIANT=cortex-a73
  TARGET_2ND_ARCH=arm
  TARGET_2ND_ARCH_VARIANT=armv8-a
  TARGET_2ND_CPU_VARIANT=cortex-a73
  HOST_ARCH=x86_64
  HOST_2ND_ARCH=x86
  HOST_OS=linux
  HOST_OS_EXTRA=Linux-4.17.0-3rodete2-amd64-x86_64-Debian-GNU/Linux-buster/sid
  HOST_CROSS_OS=windows
  HOST_CROSS_ARCH=x86
  HOST_CROSS_2ND_ARCH=x86_64
  HOST_BUILD_TYPE=release
  BUILD_ID=PI
  OUT_DIR=out
  ============================================
  [100% 2/2] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
  FAILED: out/soong/build.ninja
  out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
  error: art/build/Android.bp:318:1: dependency "dex2oat" of "com.android.art" missing variant:
    arch:android_arm_armv8-a_cortex-a73, image:core
  available variants:
    arch:android_arm64_armv8-a_cortex-a73, image:core
    arch:linux_glibc_x86_64
    arch:windows_x86
  10:52:16 soong bootstrap failed with: exit status 1

I guess that's because the logic in build/soong/apex/apex.go tries to generate all dependencies for all potential targets, but the `dex2oat` module build rules won't provide an ARM64 variant on a 64+32-bit target.

Patch-set: 9
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>