Update patch set 8
Patch Set 8:

Pre-submit error is a build failure:

  [ 75% 152581/201123] //frameworks/base/cmds/statsd:statsd clang++ src/anomaly/subscriber_util.cpp
  FAILED: out/soong/.intermediates/frameworks/base/cmds/statsd/statsd/android_arm64_armv8-2a_cortex-a75_core/obj/frameworks/base/cmds/statsd/src/anomaly/subscriber_util.o
  PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r349610/bin/clang++ -c -Iframeworks/base/cmds/statsd/src -Iframeworks/base/cmds/statsd  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8.2a -mcpu=cortex-a55 -Iout/soong/.intermediates/frameworks/base/cmds/statsd/statsd/android_arm64_armv8-2a_cortex-a75_core/gen/proto/frameworks/base/cmds/statsd -Iout/soong/.intermediates/frameworks/base/cmds/statsd/statsd/android_arm64_armv8-2a_cortex-a75_core/gen/proto -Iout/soong/.intermediates/frameworks/base/cmds/statsd/statsd/android_arm64_armv8-2a_cortex-a75_core/gen/aidl -Ihardware/interfaces/health/2.0/utils/libhealthhalutils/include -Iexternal/protobuf/src -Isystem/core/base/include -Iframeworks/native/libs/binder/include -Isystem/core/libcutils/include -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/liblog/include -Isystem/core/libsystem/include -Isystem/core/libprocessgroup/include -Iout/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_arm64_armv8-2a_cortex-a75_core_shared/gen/aidl -Iframeworks/base/libs/incident/include -Iout/soong/.intermediates/frameworks/base/libs/incident/libincident/android_arm64_armv8-2a_cortex-a75_core_shared/gen/aidl -Iout/soong/.intermediates/frameworks/base/libs/incident/libincident/android_arm64_armv8-2a_cortex-a75_core_shared/gen/proto/frameworks/base/libs/incident -Iout/soong/.intermediates/frameworks/base/libs/incident/libincident/android_arm64_armv8-2a_cortex-a75_core_shared/gen/proto -Iframeworks/base/libs/services/include -Iframeworks/base/libs/protoutil/include -Iout/soong/.intermediates/frameworks/base/tools/stats_log_api_gen/statslog.h/gen -Ihardware/libhardware/include -Isystem/media/audio/include -Isystem/bt/types -Ihardware/libhardware_legacy/include -Isystem/libhidl/base/include -Isystem/libhidl/transport/include -Iout/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.1/android.hidl.manager@1.1_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager@1.2_genc++_headers/gen -Iout/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen -Isystem/libhwbinder/include -Iout/soong/.intermediates/frameworks/hardware/interfaces/stats/1.0/android.frameworks.stats@1.0_genc++_headers/gen -Iout/soong/.intermediates/hardware/interfaces/health/1.0/android.hardware.health@1.0_genc++_headers/gen -Iout/soong/.intermediates/hardware/interfaces/health/2.0/android.hardware.health@2.0_genc++_headers/gen -Iout/soong/.intermediates/hardware/interfaces/power/1.0/android.hardware.power@1.0_genc++_headers/gen -Iout/soong/.intermediates/hardware/interfaces/power/1.1/android.hardware.power@1.1_genc++_headers/gen -Iout/soong/.intermediates/hardware/interfaces/power/stats/1.0/android.hardware.power.stats@1.0_genc++_headers/gen -Isystem/core/libpackagelistparser/include -Isystem/core/libsysutils/include -Iexternal/googletest/googletest/include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Ibionic/libc/include -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -Ilibnativehelper/include_jni -Wall -Wextra -Werror -Wno-unused-parameter -Os -DVERY_VERBOSE_PRINTING -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -DANDROID_STRICT -DGOOGLE_PROTOBUF_NO_RTTI -fPIE -D_USING_LIBCXX -std=gnu++17 -Wsign-promo -Wno-inconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF out/soong/.intermediates/frameworks/base/cmds/statsd/statsd/android_arm64_armv8-2a_cortex-a75_core/obj/frameworks/base/cmds/statsd/src/anomaly/subscriber_util.o.d -o out/soong/.intermediates/frameworks/base/cmds/statsd/statsd/android_arm64_armv8-2a_cortex-a75_core/obj/frameworks/base/cmds/statsd/src/anomaly/subscriber_util.o frameworks/base/cmds/statsd/src/anomaly/subscriber_util.cpp
  frameworks/base/cmds/statsd/src/anomaly/subscriber_util.cpp:26:10: fatal error: 'frameworks/base/libs/incident/proto/android/os/header.pb.h' file not found
  #include "frameworks/base/libs/incident/proto/android/os/header.pb.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

Restarting Treehugger.

Patch-set: 8
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>