ART: Regression Test for JDK9 update.
The tests (run in android_root mode) started to fail after
"Build with OpenJDK 9" CL:
https://android-review.googlesource.com/#/c/platform/build/+/570284/

With an error:

"Exception in thread "main" java.lang.NoSuchMethodError: No virtual
method limit(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer;
or its super classes (declaration of 'java.nio.ByteBuffer' appears
in /data/local/tmp/system/framework/core-oj.jar)"

if "export EXPERIMENTAL_USE_OPENJDK9=false" used the test succeeds.

Test: 162-method-resolution.

Change-Id: I983c2435fe87bbdb5622f8cbf318e2f1218994b0