Update patch set 2
Patch Set 2:

I believe this change broke MAC builds. Can we please fix or revert ASAP? Thanks!


FAILED: out/soong/.intermediates/art/runtime/libartd/darwin_x86_static/obj/art/runtime/fault_handler.o
 /Users/ogunwale/goma/gomacc prebuilts/clang/host/darwin-x86/clang-r328903/bin/clang++ -c -Iart/runtime -Iexternal/vixl/src -Iart/sigchainlib -Iexternal/icu/icu4c/source/common -Iexternal/lz4/lib -Iexternal/zlib -Iart/runtime  -fPIC -funwind-tables -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -DMACOSX_DEPLOYMENT_TARGET=10.8 -integrated-as -fstack-protector-strong -m32 -msse3 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -Wno-deprecated-register -Wno-sign-compare   -Iart/cmdline -Ilibnativehelper/header_only_include -Ilibnativehelper/platform_include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Isystem/core/libnativebridge/include -Isystem/core/libnativeloader/include -Isystem/core/libbacktrace/include -Isystem/core/demangle/include -Iexternal/lz4/lib -Isystem/core/liblog/include -Isystem/core/libcutils/include -Isystem/core/base/include -Iart/libartbase -Iart/libdexfile -Iart/libprofile -Iexternal/zlib -Iout/soong/.intermediates/art/runtime/art_operator_srcs/gen -Iout/soong/.intermediates/art/tools/cpp-define-generator/cpp-define-generator-asm-support/gen -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Ilibnativehelper/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include  -Ilibnativehelper/include_jni -fno-rtti -ggdb3 -Wall -Werror -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wthread-safety -Wthread-safety-negative -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -O3 -DART_DEFAULT_GC_TYPE_IS_CMS -DIMT_SIZE=43 -DART_USE_READ_BARRIER=1 -DART_READ_BARRIER_TYPE_IS_BAKER=1 -DART_DEFAULT_COMPACT_DEX_LEVEL=fast -DART_STACK_OVERFLOW_GAP_arm=8192 -DART_STACK_OVERFLOW_GAP_arm64=8192 -DART_STACK_OVERFLOW_GAP_mips=16384 -DART_STACK_OVERFLOW_GAP_mips64=16384 -DART_STACK_OVERFLOW_GAP_x86=8192 -DART_STACK_OVERFLOW_GAP_x86_64=8192 -DUSE_D8_DESUGAR=1 -DBUILDING_LIBART=1 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DVIXL_DEBUG -UNDEBUG -O2 -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_arm -DART_ENABLE_CODEGEN_arm64 -DART_ENABLE_CODEGEN_mips -DART_ENABLE_CODEGEN_mips64 -DART_ENABLE_CODEGEN_x86 -DART_ENABLE_CODEGEN_x86_64 -Wframe-larger-than=1736 -DART_FRAME_SIZE_LIMIT=1736 -DART_BASE_ADDRESS=0x60000000 -DART_BASE_ADDRESS_MIN_DELTA=-0x1000000 -DART_BASE_ADDRESS_MAX_DELTA=0x1000000 -Wno-frame-larger-than= -target i686-apple-darwin -B/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -DANDROID_STRICT -fPIC -D_USING_LIBCXX -std=gnu++14 -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next   -D_LIBCPP_DISABLE_AVAILABILITY -nostdinc++ -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-c++98-compat-extra-semi -MD -MF out/soong/.intermediates/art/runtime/libartd/darwin_x86_static/obj/art/runtime/fault_handler.o.d -o out/soong/.intermediates/art/runtime/libartd/darwin_x86_static/obj/art/runtime/fault_handler.o art/runtime/fault_handler.cc
art/runtime/fault_handler.cc:118:10: error: no viable conversion from returned value of type 'ObjPtr<mirror::Class>' to function return type 'mirror::Class *'
  return method_obj->GetDeclaringClassUnchecked<kWithoutReadBarrier>();
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
09:16:58 ninja failed with: exit status 1

#### failed to build some targets (04:27 (mm:ss)) ####

Patch-set: 2
CC: Gerrit User 1057059 <1057059@85c56323-6fa9-3386-8a01-6480fb634889>