Bisection bug search script
Introduces a python script to perform bisection bug search using
compiled-methods and run-passes dex2oat switches. Script accepts
a misbehaving program and correct output for the program and attempts
to narrow down the issue to a single method and pass. More specyfically
it tries to find such method M and pass P that when compiling only
method M with optimizations up to but _excluding_ pass P and interpreting
all other methods program gives correct output, but when compiling only
method M with optimizations up to and _including_ pass P and interpreting
all other methods program gives incorrect output.

Test:
Manual testing, example:
1. Download:
https://drive.google.com/open?id=0B-J3UL0pHz9pN2R5T2gxVHFrelE
https://drive.google.com/open?id=0B-J3UL0pHz9pUU94RGVvenBmRUU
2. Save in aosp root as classes.dex and out_int
3. Cd to aosp root and run:
./art/tools/bisection-search.py -cp classes.dex --correct_output out_int
--host Test19742
4. Verify output and logfile for lack of errors
5. Run:
./art/tools/bisection-search.py -cp classes.dex --correct_output out_int
Test19742
6. Verify that output is
AssertionError: Testable fails with no methods compiled.

Change-Id: Ic40a82184975d42c9a403f697995e5c9654b8e52