Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> >   Error: 'LSL' operator not allowed at operand 3 -- `add x20,x1,w0,lsl#1'
> 
> Try s/lsl/uxtw/ .

If GNU follows the ARM docs it must be uxtw:

ADD Xd|SP, Xn|SP, Rm{, extend {#amount}} ; 64-bit

extend
64-bit general registers
Can be one of UXTB, UXTH, UXTW, LSL|UXTX, SXTB, SXTH, SXTW or SXTX.
If Rd or Rn is SP then LSL is preferred rather than UXTX, and can be omitted when amount is 0. In all other cases extend is required and must be UXTX rather than LSL.

Patch-set: 4