Update patch set 36
Patch Set 36: Presubmit-Ready+1

Still no repro though I was using master-art instead of master-art-host and also running lunch.

The closest I've got locally is a failure to build the test due to the wrong version of java being picked up. The bot seems to be still using the OpenJDK 8 compiler.

$ mkdir master-art-host
$ cd master-art-host
$ repo init -u persistent-https://googleplex-android.git.corp.google.com/platform/manifest -b master-art-host
$ art/test/run-test --always-clean --dev --dex2oat-jobs 4 --host --prebuild --compact-dex-level fast --interpreter --no-relocate --runtime-option -Xcheck:jni --64 --build-with-javac-dx  712-varhandle-invocations
...
src2/ArrayElementGetAndBitwiseAndReleaseLong.java:4: error: cannot find symbol
import java.lang.invoke.VarHandle;
                       ^
  symbol:   class VarHandle
  location: package java.lang.invoke
...

Trying now moving src to src-art. This works with some versions of the Java 8 compiler, but the one on the bot looks a bit older.

Patch-set: 36
Reviewer: Gerrit User 1071150 <1071150@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1