Update patch set 1
Patch Set 1:

Because when I add the extra code to test for MAX_INT it's probably just as messy:

./run-test --no-prebuild 082-inline-execute
/local/home/crl/src/aosp/art/test/082-inline-execute: building...
/local/home/crl/src/aosp/art/test/082-inline-execute: running...
/local/home/crl/src/aosp/art/test/082-inline-execute: FAILED!
 
#################### info
# Test all intrinsics.#################### diffs
--- expected.txt	2016-04-08 16:15:03.295112060 -0700
+++ output.txt	2016-04-26 20:08:34.128354449 -0700
@@ -0,0 +1,8 @@
+Exception in thread "main" junit.framework.AssertionFailedError: expected:<-2147483648> but was:<2147483647>
+	at junit.framework.Assert.fail(Assert.java:50)
+	at junit.framework.Assert.failNotEquals(Assert.java:287)
+	at junit.framework.Assert.assertEquals(Assert.java:67)
+	at junit.framework.Assert.assertEquals(Assert.java:199)
+	at junit.framework.Assert.assertEquals(Assert.java:205)
+	at Main.test_Math_round_F(Main.java:849)
+	at Main.main(Main.java:42)
####################
 
082-inline-execute files left in /tmp/crl/test-24071 on host
and in /data/run-test/test-24071 on target

I can fix the bug in the algorithm you cite below, and do an instruction count of the two different methods, to get some idea of their relative performance but I probably won't report on that until some time tomorrow (April 27th).

Patch-set: 1
Label: Verified=0