Update patch set 2
Patch Set 2:

Looks like reverting it is causing more trouble than a test failure?

art/libartbase/base/systrace.h:31: error: undefined reference to 'PaletteTraceEnabled'
art/libartbase/base/systrace.h:39: error: undefined reference to 'PaletteTraceBegin'
art/libartbase/base/systrace.h:43: error: undefined reference to 'PaletteTraceEnd'
art/libartbase/base/systrace.h:31: error: undefined reference to 'PaletteTraceEnabled'
art/libartbase/base/systrace.h:39: error: undefined reference to 'PaletteTraceBegin'
art/libartbase/base/systrace.h:43: error: undefined reference to 'PaletteTraceEnd'
art/libartbase/base/systrace.h:31: error: undefined reference to 'PaletteTraceEnabled'
art/libartbase/base/systrace.h:39: error: undefined reference to 'PaletteTraceBegin'
art/libartbase/base/systrace.h:43: error: undefined reference to 'PaletteTraceEnd'
art/libartbase/base/systrace.h:43: error: undefined reference to 'PaletteTraceEnd'
art/libartbase/base/systrace.h:31: error: undefined reference to 'PaletteTraceEnabled'
art/libartbase/base/systrace.h:39: error: undefined reference to 'PaletteTraceBegin'
art/libartbase/base/systrace.h:47: error: undefined reference to 'PaletteTraceIntegerValue'
art/libartbase/base/systrace.h:47: error: undefined reference to 'PaletteTraceIntegerValue'
art/runtime/jdwp/jdwp_socket.cc:301: warning: Using 'gethostbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
art/runtime/jit/jit.cc:222: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
art/runtime/oat_file.cc:1128: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
art/runtime/thread.cc:4249: error: undefined reference to 'PaletteSchedSetPriority'
art/runtime/thread.cc:4249: error: undefined reference to 'PaletteSchedSetPriority'
art/runtime/thread.cc:4256: error: undefined reference to 'PaletteSchedGetPriority'
art/runtime/plugin.cc:36: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
art/runtime/plugin.cc:36: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
system/core/libnativeloader/native_loader.cpp:726: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
system/core/libnativebridge/native_bridge.cc:223: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
system/core/liblog/logprint.cpp:1628: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

Patch-set: 2
Reviewer: Gerrit User 1347854 <1347854@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Build-Cop-Override=0