Update patch set 2
Patch Set 2:

> Patch Set 2: Presubmit-Ready+1
> 
> Treehugger failure is a flake; restarting presubmits.

Sorry, this comment was meant for another bug (https://android-review.googlesource.com/c/platform/art/+/759681).

The Treehugger failure for this CL is:

  DIST_DIR=/buildbot/dist_dirs/git_master-art-host-linux-art-test/P6681451/0 ./art/test/testrunner/run_build_test_target.py -j80 art-test
  gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4 Copyright (C) 2013 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  openjdk version "1.8.0_45-internal" OpenJDK Runtime Environment (build 1.8.0_45-internal-b14) OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
  Traceback (most recent call last):
  File "/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py", line 1050, in <module>
  main()
  File "/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py", line 1005, in main
  gather_test_info()
  File "/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py", line 165, in gather_test_info
  DISABLED_TEST_CONTAINER = get_disabled_test_info()
  File "/usr/local/google/buildbot/src/googleplex-android/master-art-host/art/test/testrunner/testrunner.py", line 678, in get_disabled_test_info
  known_failures_info = json.loads(known_failures_json.read())
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
  return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
  obj, end = self.scan_once(s, idx)
  ValueError: Expecting ',' delimiter: line 24 column 25 (char 885)

There are missing commas in the test stanza I added to art/test/knownfailures.json.

Patch-set: 2
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>