Update patch set 4
Patch Set 4:

> FAIL: Some checks failed. See below.

[…]

 > === git_master/angler-userdebug_fastbuild3b_linux ===
 > 
 > FAIL: Failed to build git_master/angler-userdebug_fastbuild3b_linux.
 > See https://android-build.googleplex.com/builds/pending/P3827938/angler-userdebug_fastbuild3b_linux/latest.

This build error is due to an increase in generated code size.  I'll prepare a companion change to blacklist one or two more apps from the Dex pre-opt modules list(s).

  error: ext4_allocate_best_fit_partial: failed to allocate 2028 blocks, out of space?
  Creating filesystem with parameters:
      Size: 3170938880
      Block size: 4096
      Blocks per group: 32768
      Inodes per group: 8080
      Inode size: 256
      Journal blocks: 12096
      Label: system
      Blocks: 774155
      Block groups: 24
      Reserved block group size: 191
  Out of space? the tree size of out/target/product/angler/system is (MB): 
  2943	out/target/product/angler/system
  The max is 3072 MB.

Patch-set: 4