Don't wrap VerifyError into NoClassDefFoundError.
Follow RI behavior by returning the VerifyError. NoClassDefFoundError
only wraps initializer errors.

Also rename the field in ClassExt from verifyError to
erroneousStateError for better clarity.

And remove now unused feature of storing a class in the verifyError
field.

Test: test.py
Test: 824-verification-rethrow
Bug: 28313047
Change-Id: I19383f7b74f22a62ab1e0b8a13bea75a14c7b33f